name: Update mobileconfig

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest release asset URL
        id: get_url
        run: |
          API_URL="https://api.github.com/repos/dns-khoindvn/top-country-stats/releases/latest"
          DOWNLOAD_URL=$(curl -s $API_URL | grep browser_download_url | grep mobileconfig | cut -d '"' -f 4)
          echo "url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT

      - name: Download latest file
        run: |
          mkdir -p dns
          curl -L "${{ steps.get_url.outputs.url }}" -o dns/khoindvn.io.vn.mobileconfig

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dns/khoindvn.io.vn.mobileconfig
          git commit -m "Update mobileconfig" || echo "No changes"
          git push
